\c mellow

CREATE TABLE IF NOT EXISTS rooms (
  id SERIAL PRIMARY KEY NOT NULL,
  type VARCHAR(10000) NOT NULL,
  url VARCHAR(10000) NOT NULL
);

CREATE TABLE IF NOT EXISTS studio_furn (
  id SERIAL PRIMARY KEY NOT NULL,
  type VARCHAR(10000) NOT NULL,
  url VARCHAR(10000) NOT NULL,
  rooms_id INTEGER REFERENCES rooms(id)
);

CREATE TABLE IF NOT EXISTS explore (
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  url TEXT NOT NULL 
)
