\c mellow

CREATE TABLE IF NOT EXISTS rooms (
  id SERIAL PRIMARY KEY NOT NULL,
  type VARCHAR(10000) NOT NULL,
  title TEXT NOT NULL,
  url VARCHAR(10000) NOT NULL,
  description VARCHAR(10000) NOT NULL
);

CREATE TABLE IF NOT EXISTS furniture (
  id SERIAL PRIMARY KEY NOT NULL,
  room VARCHAR(10000) NOT NULL,
  couch_name VARCHAR(10000) NOT NULL,
  couch_url VARCHAR(10000) NOT NULL,
  bed_name VARCHAR(10000) NOT NULL,
  bed_url VARCHAR(10000) NOT NULL,
  table_name VARCHAR(10000) NOT NULL,
  table_url VARCHAR(10000) NOT NULL,
  cabinet_name VARCHAR(10000) NOT NULL,
  cabinet_url VARCHAR(10000) NOT NULL,
  rug_name VARCHAR(10000) NOT NULL,
  rug_url VARCHAR(10000) NOT NULL,
  tv_name VARCHAR(10000) NOT NULL,
  tv_url VARCHAR(10000) NOT NULL,
  rooms_id INTEGER REFERENCES rooms(id)
);

CREATE TABLE IF NOT EXISTS explore (
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  profile_url VARCHAR(10000) NOT NULL,
  url TEXT NOT NULL,
  title TEXT NOT NULL,
  size INTEGER,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS furniture_list (
  id SERIAL PRIMARY KEY NOT NULL,
  url TEXT NOT NULL,
  title TEXT NOT NULL,
  store TEXT NOT NULL,
  short_desc TEXT NOT NULL,
  long_desc TEXT NOT NULL
)
