\c mellow

CREATE TABLE IF NOT EXISTS rooms (
  id SERIAL PRIMARY KEY NOT NULL,
  type VARCHAR(10000) NOT NULL,
  title TEXT NOT NULL,
  url VARCHAR(10000) NOT NULL,
  description VARCHAR(10000) NOT NULL
);

CREATE TABLE IF NOT EXISTS furniture (
  id SERIAL PRIMARY KEY NOT NULL,
  room VARCHAR(10000) NOT NULL,
  couch_name VARCHAR(10000) NOT NULL,
  couch_url VARCHAR(10000) NOT NULL,
  bed_name VARCHAR(10000) NOT NULL,
  bed_url VARCHAR(10000) NOT NULL,
  table_name VARCHAR(10000) NOT NULL,
  table_url VARCHAR(10000) NOT NULL,
  cabinet_name VARCHAR(10000) NOT NULL,
  cabinet_url VARCHAR(10000) NOT NULL,
  rooms_id INTEGER REFERENCES rooms(id)
);

CREATE TABLE IF NOT EXISTS explore (
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  url TEXT NOT NULL
);
